### ISSUE TITLE
[META] Template for new issues

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#1]
## Goal:

[One line goal description] 
## Success:

[What would success look like] 
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Owner: 
Involved: 
## Required:
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: 30.06.2016) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: 30.06.2016) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: 30.06.2016)
