### ISSUE TITLE
[meta] Document Contribution Areas

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#10]
## Goal:

Document Contribution Areas within the Mozilla Switzerland with a responsible person for each of them. This should be on the Mozilla Wiki.
## Success:

Have a page on the wiki which explains all contribution areas, communication channels within the community, contact persons and example contributions.
## Roles:

Owner: @MichaelKohler
Involved: @mozillach/community-developers 
## Required:
- [x] Create an initial list of areas (@MichaelKohler, small, Due: 28.02.2016)
- [x] Create a general wiki page about Switzerland (??, medium, Due: 28.02.2016)
- [ ] Document the areas on the wiki page (??, medium, Due: 28.02.2016)
- [ ] Identify missing contact persons (??, medium, Due: 10.03.2016)
- [ ] Identify in which areas we need more people (??, medium, Due: 15.03.2016)
- [ ] Have a final version of the wiki page (@MichaelKohler, medium, Due: 31.03.2016)

**Comment by MichaelKohler** [comment]
I've added a few more contribution areas, I think we're more or less complete now. There are probably still some areas missing, but since it's a wiki, everybody can add their own areas as well :)
