### ISSUE TITLE
[meta] Create Community Development Focus Group

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#11]
## Goal:

Create a focus group which is the "last instance" to decide if a given change is implemented within the community or not. This group consists of at least 3 people and is open to everyone who wants to contribute in that direction.
## Success:

New ideas are discussed in the whole group, with the focus group having the final say if there is no agreement before. The focus group is open to everyone who wants to contribute, with optimally a rotating membership structure.
## Roles:

Owner: @mozillach/community-developers 
Involved: Nuke
## Required:
- [x] Call for participants (@MichaelKohler, small, Due: 28.02.2016)
- [x] Document responsibilities (@MichaelKohler, medium, Due: 04.03.2016)
- [ ] Document the group on the wiki page (??, medium, Due: 15.03.2016)
- [ ] Have a group established (??, medium, Due: 18.03.2016)

**Comment by MichaelKohler** [comment]
I've added Martin to the focus group as well. Currently 2 people should be enough, in case we see that the focus group is really needed, we will reach out again to have more members. For now we could cover decisions in case we would need it (as stated before, we haven't had that in the past, so I don't think we will have anything in the future as well :))
