### ISSUE TITLE
[meta] Organize a hackathon in Romandie in March

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#12]
## Goal:

Organize a hackathon in Lausanne (?) in March to kickstart our efforts to expand to the Romandie.
## Success:

We organized a hackathon with at least 10 people and have at least 5 people interested in joining further meetups and events in the region. At least 3 persons are willing to coordinate the organization of a future meetup.
## Roles:

Owner: @mozillach/community-developers 
Involved: Liip
## Required:
- [x] Find a topic (??, small, Due: 15.02.2016)
- [x] Create an initial TODO list (???, medium, Due: 18.02.2016)
- [x] Organize the final hackathon (??, medium, Due: 28.02.2016)
- [x] Promote the hackathon (??, medium, Due: 05.03.2016)

**Comment by MichaelKohler** [comment]
What do you all think about an IoT kickstart hackathon to work on ideas for maybe future Mozilla projects as announced last week? (https://discourse.mozilla-community.org/t/firefox-os-connected-devices-announcement/6864/92)

**Comment by freaktechnik** [comment]
We should check with @mozfr if they have or know of some promotion channels that we should use.

**Comment by MichaelKohler** [comment]
This will be on April 2nd in Lausanne.
